-- users
ALTER TABLE users ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ALTER COLUMN joined TYPE TIMESTAMP WITH TIME ZONE;
-- photos
ALTER TABLE photos ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE photos ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;
